export const Loans = [
    {
        id: 1,
        fullName: 'Somkene Bryan Chukwuma',
        email: 'kene@yahoo.com',
        date: '20/02/2020',
        amount: 5000,
        verified: 'No',
        approved: 'No', 
        user:   {
            id: 1,
            fullName: 'Somkene Bryan Chukwuma',
            email: 'kene@yahoo.com',
            date: '20/02/2020',
            amount: 5000,
            repayment: 4000,
            balance:  1000,
            homeAddress: 'road 17 diamond estate',
            officeAddress: 'ikeja',
            verified: 'No',
            approved: 'No'
        },
    },
    {
        id: 2,
        fullName: 'Amaka Chuks',
        email: 'amaka@yahoo.com',
        date: '25/02/2020',
        amount: 10000,
        verified: 'No',
        approved: 'No',
        user: {
            id: 2,
            fullName: 'Amaka Chuks',
            email: 'amaka@yahoo.com',
            date: '25/02/2020',
            amount: 10000,
            repayment: 6000,
            balance:  4000,
            homeAddress: 'wakefiled west yorkshire',
            officeAddress: 'middlesbrough',
            verified: 'No',
            approved: 'No'
        },
    },
    {
        id: 3,
        fullName: 'Somy Enyokwa',
        email: 'somi@yahoo.com',
        date: '15/03/2020',
        amount: 9000,
        verified: 'No',
        approved: 'No',
        user: {
            id: 3,
            fullName: 'Somy Enyokwa',
            email: 'somi@yahoo.com',
            date: '15/03/2020',
            amount: 9000,
            repayment: 6000,
            balance:  5000,
            homeAddress: 'wakefiled west yorkshire',
            officeAddress: 'middlesbrough',
            verified: 'No',
            approved: 'No'
        },
    },
    {
        id: 4,
        fullName: 'Simdi Enyokwa',
        email: 'simdi@yahoo.com',
        date: '12/01/2020',
        amount: 20000,
        verified: 'No',
        approved: 'No',
        user: {
            id: 4,
            fullName: 'Simdi Enyokwa',
            email: 'simdi@yahoo.com',
            date: '12/01/2020',
            amount: 20000,
            repayment: 6000,
            balance:  14000,
            homeAddress: 'wakefiled west yorkshire',
            officeAddress: 'middlesbrough',
            verified: 'No',
            approved: 'No'
        }
    }
]

export const DetailLoans = [
    {
        id: 1,
        fullName: 'Somkene Bryan Chukwuma',
        email: 'kene@yahoo.com',
        date: '20/02/2020',
        amount: 5000,
        repayment: 4000,
        balance:  1000,
        homeAddress: 'road 17 diamond estate',
        officeAddress: 'ikeja',
        verified: 'No',
        approved: 'No'
    },
    {
        id: 2,
        fullName: 'Amaka Chuks',
        email: 'amaka@yahoo.com',
        date: '25/02/2020',
        amount: 10000,
        repayment: 6000,
        balance:  4000,
        homeAddress: 'wakefiled west yorkshire',
        officeAddress: 'middlesbrough',
        verified: 'No',
        approved: 'No'
    },
    {
        id: 3,
        fullName: 'Somy Enyokwa',
        email: 'somi@yahoo.com',
        date: '15/03/2020',
        amount: 9000,
        repayment: 6000,
        balance:  5000,
        homeAddress: 'wakefiled west yorkshire',
        officeAddress: 'middlesbrough',
        verified: 'No',
        approved: 'No'
    },
    {
        id: 4,
        fullName: 'Simdi Enyokwa',
        email: 'simdi@yahoo.com',
        date: '12/01/2020',
        amount: 20000,
        repayment: 6000,
        balance:  14000,
        homeAddress: 'wakefiled west yorkshire',
        officeAddress: 'middlesbrough',
        verified: 'No',
        approved: 'No'
    }
]